// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zagiiqfvnagnhizdciwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZ2lpcWZ2bmFnbmhpemRjaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDgzNjQsImV4cCI6MjA1Mjk4NDM2NH0.9nBuE3LsIH1Mm11rg3Pzw6Zyy_wnPJMPw_guBLyuafs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);